import { StyleSheet, Dimensions } from 'react-native';
import { font } from '../utils/fontFamilies';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  // --- Original Styles ---
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  logoSection: {
    alignItems: 'center',
    marginBottom: 32,
    width: 240,
  },
  logoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 0,
  },
  supplierText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontFamily: font.REGULAR,
    textTransform: 'capitalize',
  },
  tagline: {
    fontSize: 24,
    color: '#000000',
    textAlign: 'center',
    fontFamily: font.MEDIUM,
    lineHeight: 32,
    maxWidth: width * 0.8,
  },
  boldText: {
    fontWeight: 'bold',
  },
  loginContainer: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  loginScrollContainer: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 40,
    alignItems: 'center',
  },
  loginHeader: {
    alignItems: 'center',
    marginBottom: 16,
    width: '100%',
  },
  welcomeText: {
    fontSize: 32,
    color: '#000000',
    marginTop: 20,
    marginBottom: 16,
    textAlign: 'center',
    fontFamily: font.BOLD,
  },
  loginSubtitle: {
    fontSize: 14,
    color: '#78828A',
    textAlign: 'center',
    lineHeight: 22,
    fontFamily: font.MEDIUM,
    marginBottom: 8,
  },
  inputContainer: {
    width: '100%',
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 14,
    color: '#111111',
    fontFamily: font.MEDIUM,
    marginBottom: 8,
    marginLeft: 4,
  },
  inputField: {
    backgroundColor: '#FFFFFF',
    borderRadius: 72,
    paddingVertical: 16,
    paddingHorizontal: 20,
    fontSize: 14,
    color: '#000000',
    borderWidth: 1,
    fontFamily: font.MEDIUM,
    borderColor: '#E6EAF1',
  },
  rowContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: 30,
    paddingHorizontal: 4,
  },
  rememberContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: '#FF5722',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
    backgroundColor: '#FFFFFF',
  },
  checkboxChecked: {
    backgroundColor: '#FF5722',
  },
  rememberText: {
    fontSize: 14,
    color: '#333333',
    fontFamily: font.REGULAR,
  },
  forgotPasswordText: {
    fontSize: 14,
    color: '#333333',
    fontFamily: font.REGULAR,
  },
  loginButton: {
    marginBottom: 20,
  },
  loginButtonText: {},
  footerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 16,
  },
  footerText: {
    fontSize: 16,
    color: '#666666',
    fontFamily: font.REGULAR,
  },
  createAccountText: {
    fontSize: 16,
    color: '#FF5722',
    fontFamily: font.SEMI_BOLD,
    marginLeft: 5,
  },
  progressContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
    width: '100%',
    paddingHorizontal: 8,
  },
  progressBar: {
    flex: 1,
    height: 6,
    borderRadius: 40,
    marginHorizontal: 4,
  },
  activeStep: {
    backgroundColor: '#00C853',
  },
  inactiveStep: {
    backgroundColor: '#E0E0E0',
  },
  sectionTitle: {
    fontSize: 24,
    fontFamily: font.BOLD,
    color: '#000000',
    textAlign: 'center',
    marginBottom: 8,
  },
  uploadContainer: {
    width: '100%',
    borderWidth: 1.5,
    borderColor: '#FF7043',
    borderStyle: 'dashed',
    borderRadius: 15,
    backgroundColor: '#FFFFFF',
    paddingVertical: 30,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  uploadIconCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#FFF3E0',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  uploadTextContainer: {
    alignItems: 'center',
  },
  uploadMainText: {
    fontSize: 14,
    color: '#9E9E9E',
    fontFamily: font.REGULAR,
  },
  uploadSelectText: {
    fontSize: 14,
    color: '#FF5722',
    fontFamily: font.REGULAR,
  },
  uploadSubText: {
    fontSize: 12,
    color: '#BDBDBD',
    marginTop: 10,
    alignSelf: 'flex-start',
    fontFamily: font.REGULAR,
  },
  dropdownField: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },

  customHeaderContainer: {
    paddingHorizontal: 20,
    paddingTop: 10,
    backgroundColor: '#fff',
    paddingBottom: 10,
  },
  customHeaderTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  customHeaderLogoContainer: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  customHeaderActionsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
  },
  customHeaderIconButton: {
    position: 'relative',
    padding: 4,
  },
  customHeaderBadgeContainer: {
    position: 'absolute',
    top: -5,
    right: -2,
    backgroundColor: '#FF1744',
    borderRadius: 10,
    paddingHorizontal: 4,
    paddingVertical: 1,
    zIndex: 1,
    borderWidth: 1.5,
    borderColor: '#F8F9FE',
  },
  customHeaderBadgeText: {
    color: '#fff',
    fontSize: 10,
    fontFamily: font.BOLD,
  },
  customHeaderDotBadge: {
    position: 'absolute',
    top: 0,
    right: 2,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#FF1744',
    zIndex: 1,
    borderWidth: 1.5,
    borderColor: '#F8F9FE',
  },
  customHeaderWelcomeText: {
    fontSize: 18,
    fontFamily: font.SEMI_BOLD,
    color: '#000000',
  },
  customHeaderBrandName: {
    fontFamily: font.REGULAR,
    color: '#000000',
    fontWeight: 'normal',
    fontSize: 18,
  },
  customHeaderSubtitle: {
    fontSize: 14,
    fontFamily: font.REGULAR,
    color: '#7F8C8D',
    marginTop: 4,
  },

  // Main Layout
  screenContainer: {
    flex: 1,
    backgroundColor: '#F8F9FE',
  },
  dashboardScrollContent: {
    padding: 16,
  },
  headerContainer: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  headerTitle: {
    fontSize: 20,
    fontFamily: font.REGULAR,
    color: '#000000',
  },
  headerSubtitle: {
    fontSize: 14,
    color: '#7F8C8D',
    marginTop: 2,
    fontFamily: font.REGULAR,
  },

  // Dashboard Grid
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 16,
  },
  statsCard: {
    width: (width - 40) / 2, // width - (16 left + 16 right + 8 gap) / 2
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 8,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E6EAF1',
  },
  statsIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  statsContent: {
    flex: 1,
    justifyContent: 'center',
  },
  statsLabel: {
    fontSize: 12,
    color: '#666666',
    fontFamily: font.REGULAR,
    marginBottom: 4,
  },
  statsValue: {
    fontSize: 14,
    color: '#000000',
    fontFamily: font.BOLD,
  },

  chartContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 12,
    marginTop: 8,
  },
  chartHeader: {
    marginBottom: 16,
  },
  chartTitle: {
    fontSize: 16,
    fontFamily: font.BOLD,
    color: '#000000',
    marginBottom: 8,
  },
  filterRow: {
    flexDirection: 'row',
    marginBottom: 20,
    gap: 10,
  },
  filterButton: {
    paddingVertical: 6,
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EEEEEE',
  },
  activeFilterButton: {
    backgroundColor: '#000000',
    borderColor: '#000000',
  },
  filterText: {
    fontSize: 12,
    color: '#666',
    fontFamily: font.REGULAR,
  },
  activeFilterText: {
    color: '#FFFFFF',
    fontFamily: font.REGULAR,
  },

  // Tabs (Orders/Inventory)
  tabContainer: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#FFFFFF',
  },
  pillTab: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 24,
    marginRight: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E6EAF1',
    flexDirection: 'row',
    alignItems: 'center',
    height: 40,
  },
  activePillTab: {
    backgroundColor: '#000000',
    borderColor: '#000000',
  },
  pillText: {
    fontSize: 14,
    color: '#333',
    fontFamily: font.SEMI_BOLD,
  },
  activePillText: {
    color: '#FFFFFF',
  },
  badge: {
    backgroundColor: '#F1F2F6',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 2,
    marginLeft: 6,
    minWidth: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeText: {
    fontSize: 12,
    fontFamily: font.MEDIUM,
    color: '#7F8C8D',
  },
  activeBadgeText: {
    color: '#000',
  },

  // List Items
  listItemCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    marginHorizontal: 16,
    marginBottom: 16,
    elevation: 2,
  },
  orderHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  orderTitle: {
    fontSize: 16,
    fontFamily: font.REGULAR,
    color: '#000',
    flex: 1,
  },
  statusTag: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 12,
    backgroundColor: '#FFECB3',
  },
  statusText: {
    fontSize: 12,
    color: '#FF8F00',
    fontFamily: font.REGULAR,
  },
  orderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  orderDetailText: {
    fontSize: 12,
    color: '#000',
    fontFamily: font.REGULAR,
    marginLeft: 6,
  },
  actionButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 16,
  },
  actionButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
  },
  acceptButton: {
    backgroundColor: '#00C853',
    marginRight: 8,
  },
  rejectButton: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#FF1744',
    marginLeft: 8,
  },
  acceptText: {
    color: '#FFFFFF',
    fontFamily: font.REGULAR,
  },
  rejectText: {
    color: '#FF1744',
    fontFamily: font.REGULAR,
  },

  // Inventory
  productImage: {
    width: 80,
    height: 80,
    borderRadius: 8,
    backgroundColor: '#eee',
    marginRight: 12,
  },
  productCardContent: {
    flex: 1,
  },
  viewProductBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 20,
  },

  outlineButtonText: {
    fontSize: 18,
    fontFamily: font.REGULAR,
    color: '#FF4500',
  },
  // --- Add Product Screen Styles ---
  addProductLabel: {
    fontSize: 14,
    fontFamily: font.MEDIUM,
    color: '#4B5563',
    marginBottom: 8,
    marginTop: 16,
  },
  addProductInput: {
    backgroundColor: '#FFFFFF',
    borderRadius: 72,
    borderWidth: 1,
    borderColor: '#E6EAF1',
    paddingHorizontal: 16,
    height: 52,
    fontSize: 14,
    fontFamily: font.REGULAR,
    color: '#000000',
  },
  addProductDropdown: {
    backgroundColor: '#FFFFFF',
    borderRadius: 72,
    borderWidth: 1,
    borderColor: '#E6EAF1',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    height: 52,
  },
  addProductDropdownText: {
    fontSize: 14,
    fontFamily: font.REGULAR,
    color: '#9E9E9E',
  },
  addProductUploadContainer: {
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#FB923C',
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    paddingVertical: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  addProductUploadRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  uploadLabelText: {
    fontSize: 14,
    fontFamily: font.REGULAR,
    color: '#9E9E9E',
  },
  uploadSelectText: {
    fontSize: 14,
    fontFamily: font.BOLD,
    color: '#F76627',
  },
  uploadHintText: {
    fontSize: 12,
    fontFamily: font.REGULAR,
    color: '#9E9E9E',
    marginTop: 8,
  },
  addProductDescriptionContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E6EAF1',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 40,
    height: 120,
    position: 'relative',
  },
  addProductDescriptionInput: {
    fontSize: 14,
    fontFamily: font.REGULAR,
    color: '#000000',
    textAlignVertical: 'top',
    height: '100%',
  },
  addProductCharCount: {
    position: 'absolute',
    bottom: 12,
    right: 16,
    fontSize: 12,
    fontFamily: font.REGULAR,
    color: '#9E9E9E',
  },
  addProductDimensionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  addProductDimensionInput: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 72,
    borderWidth: 1,
    borderColor: '#E6EAF1',
    paddingHorizontal: 16,
    height: 52,
    fontSize: 14,
    fontFamily: font.REGULAR,
    color: '#000000',
    textAlign: 'center',
  },
  colorOptionCard: {
    backgroundColor: '#F8F9FE',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#E6EAF1',
  },
  colorOptionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  colorOptionTitle: {
    fontSize: 14,
    fontFamily: font.SEMI_BOLD,
    color: '#000000',
  },
  removeColorText: {
    fontSize: 12,
    fontFamily: font.MEDIUM,
    color: '#F83336',
  },
  addColorBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    marginTop: 8,
  },
  addColorText: {
    fontSize: 14,
    fontFamily: font.SEMI_BOLD,
    color: '#F76627',
    marginLeft: 8,
  },
  pickerContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 72,
    borderWidth: 1,
    borderColor: '#E6EAF1',
    height: 52,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    position: 'relative',
    marginBottom: 4,
  },
  pickerValueText: {
    fontSize: 14,
    fontFamily: font.REGULAR,
    color: '#000000',
    flex: 1,
  },
  pickerPlaceholderText: {
    fontSize: 14,
    fontFamily: font.REGULAR,
    color: '#9E9E9E',
    flex: 1,
  },
  pickerStyle: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    opacity: 0, // Make native picker invisible but still clickable
  },
  pickerIconContainer: {
    marginLeft: 8,
  },
  nextButtonGradient: {
    borderRadius: 30,
    marginTop: 24,
    marginBottom: 40,
    height: 56,
    overflow: 'hidden',
  },
  nextButton: {
    width: '100%',
    height: '100%',
    backgroundColor: '#F76627', // Fallback if gradient not used
    justifyContent: 'center',
    alignItems: 'center',
  },
  nextButtonText: {
    fontSize: 16,
    fontFamily: font.BOLD,
    color: '#FFFFFF',
  },
  publishButton: {
    backgroundColor: '#F76627',
    borderRadius: 30,
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 24,
    marginBottom: 40,
  },
  publishButtonText: {
    fontSize: 16,
    fontFamily: font.BOLD,
    color: '#FFFFFF',
  },
  // --- Orders Screen Styles ---
  ordersContainer: {
    flex: 1,
    backgroundColor: '#F8F9FE',
  },
  ordersHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#fff',
  },
  headerIconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E6EAF1',
  },
  ordersTitle: {
    fontSize: 18,
    fontFamily: font.BOLD,
    color: '#000000',
  },
  orderListHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  orderListTitle: {
    fontSize: 14,
    fontFamily: font.SEMI_BOLD,
    color: '#000000',
  },
  sortByContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sortByText: {
    fontSize: 14,
    fontFamily: font.REGULAR,
    color: '#333333',
    marginRight: 4,
  },
  orderCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 12,
    marginHorizontal: 16,
    marginBottom: 16,
  },
  orderCardTop: {
    flexDirection: 'row',
  },
  orderProductImage: {
    width: 75,
    height: 75,
    borderRadius: 12,
    backgroundColor: '#F5F5F5',
  },
  orderInfo: {
    flex: 1,
    marginLeft: 12,
  },
  orderInfoTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  orderProductName: {
    fontSize: 14,
    fontFamily: font.REGULAR,
    color: '#333333',
    flex: 1,
  },
  pendingTag: {
    backgroundColor: '#FFB74D',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 20,
  },
  pendingTagText: {
    fontSize: 12,
    fontFamily: font.MEDIUM,
    color: '#FFFFFF',
  },
  orderDateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },

  orderPrice: {
    fontSize: 12,
    fontFamily: font.BOLD,
    color: '#000000',
    marginVertical: 4,
  },
  orderLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
  },
  customerDivider: {
    height: 1,
    backgroundColor: '#F0F0F0',
    marginVertical: 16,
  },
  customerRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  customerAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#eee',
  },
  customerInfo: {
    marginLeft: 12,
  },
  customerLabel: {
    fontSize: 11,
    fontFamily: font.REGULAR,
    color: '#000',
  },
  customerName: {
    fontSize: 14,
    fontFamily: font.SEMI_BOLD,
    color: '#333333',
  },
  orderActionButtons: {
    flexDirection: 'row',
    marginTop: 16,
    gap: 12,
  },
  orderAcceptBtn: {
    flex: 1,
    backgroundColor: '#09A55A',
    paddingVertical: 14.5,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
  },
  orderAcceptText: {
    fontSize: 14,
    fontFamily: font.SEMI_BOLD,
    color: '#FFFFFF',
  },
  orderRejectBtn: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#F83336',
    paddingVertical: 14.5,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
  },
  orderRejectText: {
    fontSize: 14,
    fontFamily: font.SEMI_BOLD,
    color: '#F83336',
  },

  // --- Inventory Screen Styles ---
  inventoryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    marginTop: 12,
    marginBottom: 16,
  },
  inventoryTitle: {
    fontSize: 18,
    fontFamily: font.BOLD,
    color: '#000000',
  },
  addProductBtn: {
    backgroundColor: '#FF5722',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 25,
  },
  addProductText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontFamily: font.SEMI_BOLD,
    marginLeft: 6,
  },
  inventorySearchRow: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  searchBarContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 25,
    paddingHorizontal: 16,
    height: 48,
    borderWidth: 1,
    borderColor: '#E6EAF1',
  },
  searchInput: {
    flex: 1,
    marginLeft: 10,
    fontSize: 15,
    color: '#000000',
    fontFamily: font.REGULAR,
  },
  filterBtn: {
    width: 48,
    height: 48,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 12,
    borderWidth: 1,
    borderColor: '#E6EAF1',
  },
  productCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 12,
    marginHorizontal: 16,
    marginBottom: 16,
  },
  productCardTop: {
    flexDirection: 'row',
    // marginBottom: 12,
  },
  productImg: {
    width: 75,
    height: 75,
    borderRadius: 12,
    backgroundColor: '#F5F5F5',
  },
  productContent: {
    flex: 1,
    marginLeft: 12,
  },
  productTitle: {
    fontSize: 14,
    fontFamily: font.REGULAR,
    color: '#000000',
    lineHeight: 18,
    marginBottom: 8,
  },
  productDataRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  productDataLabel: {
    fontSize: 12,
    fontFamily: font.REGULAR,
    color: '#000',
  },
  productDataValue: {
    fontSize: 12,
    fontFamily: font.REGULAR,
    color: '#000000',
  },
  productDivider: {
    height: 1,
    backgroundColor: '#F0F0F0',
    marginVertical: 10,
  },
  productFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  stockContainer: {
    justifyContent: 'center',
  },
  stockLabel: {
    fontSize: 11,
    fontFamily: font.REGULAR,
    color: '#7F8C8D',
  },
  stockValue: {
    fontSize: 14,
    fontFamily: font.BOLD,
    color: '#000000',
  },
  productActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  viewDetailBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8F9FE',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: '#E6EAF1',
    marginRight: 10,
  },
  viewDetailText: {
    fontSize: 13,
    fontFamily: font.SEMI_BOLD,
    color: '#000000',
    marginLeft: 6,
  },
  shareBtn: {
    width: 44,
    height: 44,
    backgroundColor: '#F8F9FE',
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E6EAF1',
  },

  // --- Product Detail Screen Styles ---
  productDetailScroll: {
    flexGrow: 1,
    backgroundColor: '#F8F9FE',
    padding: 16,
    paddingBottom: 40,
  },
  productDetailCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 12,
  },
  productDetailFullTitle: {
    fontSize: 14,
    fontFamily: font.MEDIUM,
    color: '#333333',
    lineHeight: 18,
    marginBottom: 10,
  },
  detailSummaryRow: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  detailProductImg: {
    width: 75,
    height: 75,
    borderRadius: 12,
    backgroundColor: '#F5F5F5',
  },
  detailSummaryInfo: {
    flex: 1,
    marginLeft: 16,
    justifyContent: 'space-between',
  },
  detailDataRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  detailDataLabel: {
    fontSize: 12,
    fontFamily: font.REGULAR,
    color: '#000',
  },
  detailDataValue: {
    fontSize: 12,
    fontFamily: font.REGULAR,
    color: '#000',
  },
  detailPrice: {
    fontSize: 14,
    fontFamily: font.BOLD,
    color: '#000000',
  },
  detailStockRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#F0F0F0',
    marginBottom: 10,
  },
  detailStockLabel: {
    fontSize: 14,
    fontFamily: font.MEDIUM,
    color: '#333333',
  },
  detailStockBox: {
    width: 120,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E6EAF1',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  detailStockValue: {
    fontSize: 14,
    fontFamily: font.REGULAR,
    color: '#7F8C8D',
  },
  attributesList: {
    marginBottom: 16,
  },
  attributeItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 14,
  },
  attributeLabel: {
    fontSize: 12,
    fontFamily: font.REGULAR,
    color: '#000',
    flex: 0.5,
  },
  attributeValue: {
    fontSize: 13,
    fontFamily: font.SEMI_BOLD,
    color: '#333333',
    flex: 0.5,
    textAlign: 'right',
  },
  attributePrice: {
    fontSize: 14,
    fontFamily: font.BOLD,
    color: '#000000',
    flex: 0.5,
    textAlign: 'right',
  },
  attributeDiscount: {
    fontSize: 13,
    fontFamily: font.SEMI_BOLD,
    color: '#09A55A',
    flex: 0.5,
    textAlign: 'right',
  },

  descriptionTitle: {
    fontSize: 14,
    fontFamily: font.MEDIUM,
    color: '#333333',
    marginBottom: 12,
  },
  descriptionPoint: {
    flexDirection: 'row',
    marginBottom: 8,
    paddingLeft: 4,
  },
  bullet: {
    fontSize: 16,
    color: '#636972',
    marginRight: 8,
    lineHeight: 18,
  },
  descriptionText: {
    fontSize: 12,
    fontFamily: font.REGULAR,
    color: '#636972',
    lineHeight: 18,
    flex: 1,
    letterSpacing: 0.5,
  },

  // --- Success Screen Styles ---
  successContainer: {
    flex: 1,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  successIconContainer: {
    marginBottom: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  successTitle: {
    fontSize: 24,
    fontFamily: font.BOLD,
    color: '#111827',
    textAlign: 'center',
    marginBottom: 12,
    lineHeight: 32,
  },
  successSubtitle: {
    fontSize: 16,
    fontFamily: font.REGULAR,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 24,
    paddingHorizontal: 16,
  },
  successFooter: {
    padding: 24,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
    width: '100%',
  },
  successViewProductBtn: {
    height: 56,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: '#F76627',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    backgroundColor: '#FFFFFF',
  },
  successViewProductText: {
    fontSize: 16,
    fontFamily: font.BOLD,
    color: '#F76627',
  },
  successHomeBtnGradient: {
    height: 56,
    borderRadius: 30,
    overflow: 'hidden',
  },
  successHomeBtn: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  successHomeText: {
    fontSize: 16,
    fontFamily: font.BOLD,
    color: '#FFFFFF',
  },
});
