# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

use_modular_headers!

target 'expertspaceprovider' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
  react_native_post_install(installer, config[:reactNativePath])

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|

      # Allow React Native old C++ headers
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'

      # 🔥 KEY FIX — disable new Xcode strict module verification
      config.build_settings['CLANG_MODULES_AUTOLINK'] = 'NO'
      config.build_settings['ENABLE_MODULE_VERIFIER'] = 'NO'

      # Keep modules ON (important for UIKit)
      config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'

      # Fix Swift + Firebase coexistence
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
      config.build_settings['DEFINES_MODULE'] = 'NO'
    end
  end
end
end
